USE S13

-- SOLUTION:
-- SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM TipuriTablouri
WAITFOR DELAY '00:00:15'
SELECT * FROM TipuriTablouri
COMMIT TRAN