-- SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
SELECT * FROM Clienti
WAITFOR DELAY '00:00:15'
SELECT * FROM Clienti
COMMIT TRAN


SELECT * FROM Clienti